// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/commands.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { makeGenericClientConstructor, } from "@grpc/grpc-js";
import { Diagnostic, Empty } from "./common.ts";
function createBaseCommandContext() {
    return { filePath: undefined, selectedText: undefined, language: undefined, diagnostics: [] };
}
export const CommandContext = {
    encode(message, writer = new BinaryWriter()) {
        if (message.filePath !== undefined) {
            writer.uint32(10).string(message.filePath);
        }
        if (message.selectedText !== undefined) {
            writer.uint32(18).string(message.selectedText);
        }
        if (message.language !== undefined) {
            writer.uint32(26).string(message.language);
        }
        for (const v of message.diagnostics) {
            Diagnostic.encode(v, writer.uint32(34).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCommandContext();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.filePath = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.selectedText = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.language = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.diagnostics.push(Diagnostic.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            filePath: isSet(object.filePath) ? globalThis.String(object.filePath) : undefined,
            selectedText: isSet(object.selectedText) ? globalThis.String(object.selectedText) : undefined,
            language: isSet(object.language) ? globalThis.String(object.language) : undefined,
            diagnostics: globalThis.Array.isArray(object?.diagnostics)
                ? object.diagnostics.map((e) => Diagnostic.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.filePath !== undefined) {
            obj.filePath = message.filePath;
        }
        if (message.selectedText !== undefined) {
            obj.selectedText = message.selectedText;
        }
        if (message.language !== undefined) {
            obj.language = message.language;
        }
        if (message.diagnostics?.length) {
            obj.diagnostics = message.diagnostics.map((e) => Diagnostic.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return CommandContext.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCommandContext();
        message.filePath = object.filePath ?? undefined;
        message.selectedText = object.selectedText ?? undefined;
        message.language = object.language ?? undefined;
        message.diagnostics = object.diagnostics?.map((e) => Diagnostic.fromPartial(e)) || [];
        return message;
    },
};
export const CommandsServiceDefinition = {
    name: "CommandsService",
    fullName: "cline.CommandsService",
    methods: {
        addToCline: {
            name: "addToCline",
            requestType: CommandContext,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
        fixWithCline: {
            name: "fixWithCline",
            requestType: CommandContext,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
        explainWithCline: {
            name: "explainWithCline",
            requestType: CommandContext,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
        improveWithCline: {
            name: "improveWithCline",
            requestType: CommandContext,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
    },
};
export const CommandsServiceService = {
    addToCline: {
        path: "/cline.CommandsService/addToCline",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CommandContext.encode(value).finish()),
        requestDeserialize: (value) => CommandContext.decode(value),
        responseSerialize: (value) => Buffer.from(Empty.encode(value).finish()),
        responseDeserialize: (value) => Empty.decode(value),
    },
    fixWithCline: {
        path: "/cline.CommandsService/fixWithCline",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CommandContext.encode(value).finish()),
        requestDeserialize: (value) => CommandContext.decode(value),
        responseSerialize: (value) => Buffer.from(Empty.encode(value).finish()),
        responseDeserialize: (value) => Empty.decode(value),
    },
    explainWithCline: {
        path: "/cline.CommandsService/explainWithCline",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CommandContext.encode(value).finish()),
        requestDeserialize: (value) => CommandContext.decode(value),
        responseSerialize: (value) => Buffer.from(Empty.encode(value).finish()),
        responseDeserialize: (value) => Empty.decode(value),
    },
    improveWithCline: {
        path: "/cline.CommandsService/improveWithCline",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CommandContext.encode(value).finish()),
        requestDeserialize: (value) => CommandContext.decode(value),
        responseSerialize: (value) => Buffer.from(Empty.encode(value).finish()),
        responseDeserialize: (value) => Empty.decode(value),
    },
};
export const CommandsServiceClient = makeGenericClientConstructor(CommandsServiceService, "cline.CommandsService");
function isSet(value) {
    return value !== null && value !== undefined;
}
