// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/common.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export var DiagnosticSeverity;
(function (DiagnosticSeverity) {
    DiagnosticSeverity[DiagnosticSeverity["DIAGNOSTIC_ERROR"] = 0] = "DIAGNOSTIC_ERROR";
    DiagnosticSeverity[DiagnosticSeverity["DIAGNOSTIC_WARNING"] = 1] = "DIAGNOSTIC_WARNING";
    DiagnosticSeverity[DiagnosticSeverity["DIAGNOSTIC_INFORMATION"] = 2] = "DIAGNOSTIC_INFORMATION";
    DiagnosticSeverity[DiagnosticSeverity["DIAGNOSTIC_HINT"] = 3] = "DIAGNOSTIC_HINT";
    DiagnosticSeverity[DiagnosticSeverity["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(DiagnosticSeverity || (DiagnosticSeverity = {}));
export function diagnosticSeverityFromJSON(object) {
    switch (object) {
        case 0:
        case "DIAGNOSTIC_ERROR":
            return DiagnosticSeverity.DIAGNOSTIC_ERROR;
        case 1:
        case "DIAGNOSTIC_WARNING":
            return DiagnosticSeverity.DIAGNOSTIC_WARNING;
        case 2:
        case "DIAGNOSTIC_INFORMATION":
            return DiagnosticSeverity.DIAGNOSTIC_INFORMATION;
        case 3:
        case "DIAGNOSTIC_HINT":
            return DiagnosticSeverity.DIAGNOSTIC_HINT;
        case -1:
        case "UNRECOGNIZED":
        default:
            return DiagnosticSeverity.UNRECOGNIZED;
    }
}
export function diagnosticSeverityToJSON(object) {
    switch (object) {
        case DiagnosticSeverity.DIAGNOSTIC_ERROR:
            return "DIAGNOSTIC_ERROR";
        case DiagnosticSeverity.DIAGNOSTIC_WARNING:
            return "DIAGNOSTIC_WARNING";
        case DiagnosticSeverity.DIAGNOSTIC_INFORMATION:
            return "DIAGNOSTIC_INFORMATION";
        case DiagnosticSeverity.DIAGNOSTIC_HINT:
            return "DIAGNOSTIC_HINT";
        case DiagnosticSeverity.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseMetadata() {
    return {};
}
export const Metadata = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMetadata();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return Metadata.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseMetadata();
        return message;
    },
};
function createBaseEmptyRequest() {
    return {};
}
export const EmptyRequest = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEmptyRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return EmptyRequest.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseEmptyRequest();
        return message;
    },
};
function createBaseEmpty() {
    return {};
}
export const Empty = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEmpty();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return Empty.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseEmpty();
        return message;
    },
};
function createBaseStringRequest() {
    return { value: "" };
}
export const StringRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseStringRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? globalThis.String(object.value) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return StringRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseStringRequest();
        message.value = object.value ?? "";
        return message;
    },
};
function createBaseStringArrayRequest() {
    return { value: [] };
}
export const StringArrayRequest = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.value) {
            writer.uint32(18).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseStringArrayRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: globalThis.Array.isArray(object?.value) ? object.value.map((e) => globalThis.String(e)) : [] };
    },
    toJSON(message) {
        const obj = {};
        if (message.value?.length) {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return StringArrayRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseStringArrayRequest();
        message.value = object.value?.map((e) => e) || [];
        return message;
    },
};
function createBaseString() {
    return { value: "" };
}
export const String = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value !== "") {
            writer.uint32(10).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseString();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? globalThis.String(object.value) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return String.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseString();
        message.value = object.value ?? "";
        return message;
    },
};
function createBaseInt64Request() {
    return { value: 0 };
}
export const Int64Request = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value !== 0) {
            writer.uint32(16).int64(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseInt64Request();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.value = longToNumber(reader.int64());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? globalThis.Number(object.value) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== 0) {
            obj.value = Math.round(message.value);
        }
        return obj;
    },
    create(base) {
        return Int64Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseInt64Request();
        message.value = object.value ?? 0;
        return message;
    },
};
function createBaseInt64() {
    return { value: 0 };
}
export const Int64 = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value !== 0) {
            writer.uint32(8).int64(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseInt64();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.value = longToNumber(reader.int64());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? globalThis.Number(object.value) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== 0) {
            obj.value = Math.round(message.value);
        }
        return obj;
    },
    create(base) {
        return Int64.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseInt64();
        message.value = object.value ?? 0;
        return message;
    },
};
function createBaseBytesRequest() {
    return { value: Buffer.alloc(0) };
}
export const BytesRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value.length !== 0) {
            writer.uint32(18).bytes(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBytesRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = Buffer.from(reader.bytes());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? Buffer.from(bytesFromBase64(object.value)) : Buffer.alloc(0) };
    },
    toJSON(message) {
        const obj = {};
        if (message.value.length !== 0) {
            obj.value = base64FromBytes(message.value);
        }
        return obj;
    },
    create(base) {
        return BytesRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseBytesRequest();
        message.value = object.value ?? Buffer.alloc(0);
        return message;
    },
};
function createBaseBytes() {
    return { value: Buffer.alloc(0) };
}
export const Bytes = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value.length !== 0) {
            writer.uint32(10).bytes(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBytes();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.value = Buffer.from(reader.bytes());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? Buffer.from(bytesFromBase64(object.value)) : Buffer.alloc(0) };
    },
    toJSON(message) {
        const obj = {};
        if (message.value.length !== 0) {
            obj.value = base64FromBytes(message.value);
        }
        return obj;
    },
    create(base) {
        return Bytes.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseBytes();
        message.value = object.value ?? Buffer.alloc(0);
        return message;
    },
};
function createBaseBooleanRequest() {
    return { value: false };
}
export const BooleanRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value !== false) {
            writer.uint32(16).bool(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBooleanRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.value = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? globalThis.Boolean(object.value) : false };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== false) {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return BooleanRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseBooleanRequest();
        message.value = object.value ?? false;
        return message;
    },
};
function createBaseBoolean() {
    return { value: false };
}
export const Boolean = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value !== false) {
            writer.uint32(8).bool(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBoolean();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.value = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? globalThis.Boolean(object.value) : false };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== false) {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return Boolean.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseBoolean();
        message.value = object.value ?? false;
        return message;
    },
};
function createBaseBooleanResponse() {
    return { value: false };
}
export const BooleanResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.value !== false) {
            writer.uint32(8).bool(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBooleanResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.value = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { value: isSet(object.value) ? globalThis.Boolean(object.value) : false };
    },
    toJSON(message) {
        const obj = {};
        if (message.value !== false) {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return BooleanResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseBooleanResponse();
        message.value = object.value ?? false;
        return message;
    },
};
function createBaseStringArray() {
    return { values: [] };
}
export const StringArray = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.values) {
            writer.uint32(10).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseStringArray();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.values.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            values: globalThis.Array.isArray(object?.values) ? object.values.map((e) => globalThis.String(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.values?.length) {
            obj.values = message.values;
        }
        return obj;
    },
    create(base) {
        return StringArray.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseStringArray();
        message.values = object.values?.map((e) => e) || [];
        return message;
    },
};
function createBaseStringArrays() {
    return { values1: [], values2: [] };
}
export const StringArrays = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.values1) {
            writer.uint32(10).string(v);
        }
        for (const v of message.values2) {
            writer.uint32(18).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseStringArrays();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.values1.push(reader.string());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.values2.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            values1: globalThis.Array.isArray(object?.values1) ? object.values1.map((e) => globalThis.String(e)) : [],
            values2: globalThis.Array.isArray(object?.values2) ? object.values2.map((e) => globalThis.String(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.values1?.length) {
            obj.values1 = message.values1;
        }
        if (message.values2?.length) {
            obj.values2 = message.values2;
        }
        return obj;
    },
    create(base) {
        return StringArrays.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseStringArrays();
        message.values1 = object.values1?.map((e) => e) || [];
        message.values2 = object.values2?.map((e) => e) || [];
        return message;
    },
};
function createBaseKeyValuePair() {
    return { key: "", value: "" };
}
export const KeyValuePair = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseKeyValuePair();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return KeyValuePair.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseKeyValuePair();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function createBaseFileDiagnostics() {
    return { filePath: "", diagnostics: [] };
}
export const FileDiagnostics = {
    encode(message, writer = new BinaryWriter()) {
        if (message.filePath !== "") {
            writer.uint32(10).string(message.filePath);
        }
        for (const v of message.diagnostics) {
            Diagnostic.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFileDiagnostics();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.filePath = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.diagnostics.push(Diagnostic.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            filePath: isSet(object.filePath) ? globalThis.String(object.filePath) : "",
            diagnostics: globalThis.Array.isArray(object?.diagnostics)
                ? object.diagnostics.map((e) => Diagnostic.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.filePath !== "") {
            obj.filePath = message.filePath;
        }
        if (message.diagnostics?.length) {
            obj.diagnostics = message.diagnostics.map((e) => Diagnostic.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return FileDiagnostics.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFileDiagnostics();
        message.filePath = object.filePath ?? "";
        message.diagnostics = object.diagnostics?.map((e) => Diagnostic.fromPartial(e)) || [];
        return message;
    },
};
function createBaseDiagnostic() {
    return { message: "", range: undefined, severity: 0, source: undefined };
}
export const Diagnostic = {
    encode(message, writer = new BinaryWriter()) {
        if (message.message !== "") {
            writer.uint32(10).string(message.message);
        }
        if (message.range !== undefined) {
            DiagnosticRange.encode(message.range, writer.uint32(18).fork()).join();
        }
        if (message.severity !== 0) {
            writer.uint32(24).int32(message.severity);
        }
        if (message.source !== undefined) {
            writer.uint32(34).string(message.source);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDiagnostic();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.message = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.range = DiagnosticRange.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.severity = reader.int32();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.source = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            message: isSet(object.message) ? globalThis.String(object.message) : "",
            range: isSet(object.range) ? DiagnosticRange.fromJSON(object.range) : undefined,
            severity: isSet(object.severity) ? diagnosticSeverityFromJSON(object.severity) : 0,
            source: isSet(object.source) ? globalThis.String(object.source) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.message !== "") {
            obj.message = message.message;
        }
        if (message.range !== undefined) {
            obj.range = DiagnosticRange.toJSON(message.range);
        }
        if (message.severity !== 0) {
            obj.severity = diagnosticSeverityToJSON(message.severity);
        }
        if (message.source !== undefined) {
            obj.source = message.source;
        }
        return obj;
    },
    create(base) {
        return Diagnostic.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseDiagnostic();
        message.message = object.message ?? "";
        message.range = (object.range !== undefined && object.range !== null)
            ? DiagnosticRange.fromPartial(object.range)
            : undefined;
        message.severity = object.severity ?? 0;
        message.source = object.source ?? undefined;
        return message;
    },
};
function createBaseDiagnosticRange() {
    return { start: undefined, end: undefined };
}
export const DiagnosticRange = {
    encode(message, writer = new BinaryWriter()) {
        if (message.start !== undefined) {
            DiagnosticPosition.encode(message.start, writer.uint32(10).fork()).join();
        }
        if (message.end !== undefined) {
            DiagnosticPosition.encode(message.end, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDiagnosticRange();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.start = DiagnosticPosition.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.end = DiagnosticPosition.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            start: isSet(object.start) ? DiagnosticPosition.fromJSON(object.start) : undefined,
            end: isSet(object.end) ? DiagnosticPosition.fromJSON(object.end) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.start !== undefined) {
            obj.start = DiagnosticPosition.toJSON(message.start);
        }
        if (message.end !== undefined) {
            obj.end = DiagnosticPosition.toJSON(message.end);
        }
        return obj;
    },
    create(base) {
        return DiagnosticRange.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseDiagnosticRange();
        message.start = (object.start !== undefined && object.start !== null)
            ? DiagnosticPosition.fromPartial(object.start)
            : undefined;
        message.end = (object.end !== undefined && object.end !== null)
            ? DiagnosticPosition.fromPartial(object.end)
            : undefined;
        return message;
    },
};
function createBaseDiagnosticPosition() {
    return { line: 0, character: 0 };
}
export const DiagnosticPosition = {
    encode(message, writer = new BinaryWriter()) {
        if (message.line !== 0) {
            writer.uint32(8).int32(message.line);
        }
        if (message.character !== 0) {
            writer.uint32(16).int32(message.character);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDiagnosticPosition();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.line = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.character = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            line: isSet(object.line) ? globalThis.Number(object.line) : 0,
            character: isSet(object.character) ? globalThis.Number(object.character) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.line !== 0) {
            obj.line = Math.round(message.line);
        }
        if (message.character !== 0) {
            obj.character = Math.round(message.character);
        }
        return obj;
    },
    create(base) {
        return DiagnosticPosition.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseDiagnosticPosition();
        message.line = object.line ?? 0;
        message.character = object.character ?? 0;
        return message;
    },
};
function bytesFromBase64(b64) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return globalThis.Buffer.from(arr).toString("base64");
}
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
