// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/oca_account.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { makeGenericClientConstructor, } from "@grpc/grpc-js";
import { Empty, EmptyRequest, String } from "./common.ts";
function createBaseOcaAuthState() {
    return { user: undefined, apiKey: undefined };
}
export const OcaAuthState = {
    encode(message, writer = new BinaryWriter()) {
        if (message.user !== undefined) {
            OcaUserInfo.encode(message.user, writer.uint32(10).fork()).join();
        }
        if (message.apiKey !== undefined) {
            writer.uint32(18).string(message.apiKey);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOcaAuthState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.user = OcaUserInfo.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.apiKey = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            user: isSet(object.user) ? OcaUserInfo.fromJSON(object.user) : undefined,
            apiKey: isSet(object.apiKey) ? globalThis.String(object.apiKey) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.user !== undefined) {
            obj.user = OcaUserInfo.toJSON(message.user);
        }
        if (message.apiKey !== undefined) {
            obj.apiKey = message.apiKey;
        }
        return obj;
    },
    create(base) {
        return OcaAuthState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseOcaAuthState();
        message.user = (object.user !== undefined && object.user !== null)
            ? OcaUserInfo.fromPartial(object.user)
            : undefined;
        message.apiKey = object.apiKey ?? undefined;
        return message;
    },
};
function createBaseOcaUserInfo() {
    return { uid: "", displayName: undefined, email: undefined };
}
export const OcaUserInfo = {
    encode(message, writer = new BinaryWriter()) {
        if (message.uid !== "") {
            writer.uint32(10).string(message.uid);
        }
        if (message.displayName !== undefined) {
            writer.uint32(18).string(message.displayName);
        }
        if (message.email !== undefined) {
            writer.uint32(26).string(message.email);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOcaUserInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.uid = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.displayName = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.email = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            uid: isSet(object.uid) ? globalThis.String(object.uid) : "",
            displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : undefined,
            email: isSet(object.email) ? globalThis.String(object.email) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.uid !== "") {
            obj.uid = message.uid;
        }
        if (message.displayName !== undefined) {
            obj.displayName = message.displayName;
        }
        if (message.email !== undefined) {
            obj.email = message.email;
        }
        return obj;
    },
    create(base) {
        return OcaUserInfo.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseOcaUserInfo();
        message.uid = object.uid ?? "";
        message.displayName = object.displayName ?? undefined;
        message.email = object.email ?? undefined;
        return message;
    },
};
export const OcaAccountServiceDefinition = {
    name: "OcaAccountService",
    fullName: "cline.OcaAccountService",
    methods: {
        /**
         * Handles the user clicking the login link in the UI.
         * Generates a secure nonce for state validation, stores it in secrets,
         * and opens the authentication URL in the external browser.
         */
        ocaAccountLoginClicked: {
            name: "ocaAccountLoginClicked",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: String,
            responseStream: false,
            options: {},
        },
        /**
         * Handles the user clicking the logout button in the UI.
         * Clears API keys and user state.
         */
        ocaAccountLogoutClicked: {
            name: "ocaAccountLogoutClicked",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
        /** Subscribe to auth status update events (when authentication state changes) */
        ocaSubscribeToAuthStatusUpdate: {
            name: "ocaSubscribeToAuthStatusUpdate",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: OcaAuthState,
            responseStream: true,
            options: {},
        },
    },
};
export const OcaAccountServiceService = {
    /**
     * Handles the user clicking the login link in the UI.
     * Generates a secure nonce for state validation, stores it in secrets,
     * and opens the authentication URL in the external browser.
     */
    ocaAccountLoginClicked: {
        path: "/cline.OcaAccountService/ocaAccountLoginClicked",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(String.encode(value).finish()),
        responseDeserialize: (value) => String.decode(value),
    },
    /**
     * Handles the user clicking the logout button in the UI.
     * Clears API keys and user state.
     */
    ocaAccountLogoutClicked: {
        path: "/cline.OcaAccountService/ocaAccountLogoutClicked",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(Empty.encode(value).finish()),
        responseDeserialize: (value) => Empty.decode(value),
    },
    /** Subscribe to auth status update events (when authentication state changes) */
    ocaSubscribeToAuthStatusUpdate: {
        path: "/cline.OcaAccountService/ocaSubscribeToAuthStatusUpdate",
        requestStream: false,
        responseStream: true,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(OcaAuthState.encode(value).finish()),
        responseDeserialize: (value) => OcaAuthState.decode(value),
    },
};
export const OcaAccountServiceClient = makeGenericClientConstructor(OcaAccountServiceService, "cline.OcaAccountService");
function isSet(value) {
    return value !== null && value !== undefined;
}
