// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: host/env.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { makeGenericClientConstructor, } from "@grpc/grpc-js";
import { Empty, EmptyRequest, String, StringRequest } from "../cline/common.ts";
export var Setting;
(function (Setting) {
    /** UNSUPPORTED - This host does not support this setting. */
    Setting[Setting["UNSUPPORTED"] = 0] = "UNSUPPORTED";
    Setting[Setting["ENABLED"] = 1] = "ENABLED";
    Setting[Setting["DISABLED"] = 2] = "DISABLED";
    Setting[Setting["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(Setting || (Setting = {}));
export function settingFromJSON(object) {
    switch (object) {
        case 0:
        case "UNSUPPORTED":
            return Setting.UNSUPPORTED;
        case 1:
        case "ENABLED":
            return Setting.ENABLED;
        case 2:
        case "DISABLED":
            return Setting.DISABLED;
        case -1:
        case "UNRECOGNIZED":
        default:
            return Setting.UNRECOGNIZED;
    }
}
export function settingToJSON(object) {
    switch (object) {
        case Setting.UNSUPPORTED:
            return "UNSUPPORTED";
        case Setting.ENABLED:
            return "ENABLED";
        case Setting.DISABLED:
            return "DISABLED";
        case Setting.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseGetHostVersionResponse() {
    return { platform: undefined, version: undefined, clineType: undefined, clineVersion: undefined };
}
export const GetHostVersionResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.platform !== undefined) {
            writer.uint32(10).string(message.platform);
        }
        if (message.version !== undefined) {
            writer.uint32(18).string(message.version);
        }
        if (message.clineType !== undefined) {
            writer.uint32(26).string(message.clineType);
        }
        if (message.clineVersion !== undefined) {
            writer.uint32(34).string(message.clineVersion);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetHostVersionResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.platform = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.version = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.clineType = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.clineVersion = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            platform: isSet(object.platform) ? globalThis.String(object.platform) : undefined,
            version: isSet(object.version) ? globalThis.String(object.version) : undefined,
            clineType: isSet(object.clineType) ? globalThis.String(object.clineType) : undefined,
            clineVersion: isSet(object.clineVersion) ? globalThis.String(object.clineVersion) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.platform !== undefined) {
            obj.platform = message.platform;
        }
        if (message.version !== undefined) {
            obj.version = message.version;
        }
        if (message.clineType !== undefined) {
            obj.clineType = message.clineType;
        }
        if (message.clineVersion !== undefined) {
            obj.clineVersion = message.clineVersion;
        }
        return obj;
    },
    create(base) {
        return GetHostVersionResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetHostVersionResponse();
        message.platform = object.platform ?? undefined;
        message.version = object.version ?? undefined;
        message.clineType = object.clineType ?? undefined;
        message.clineVersion = object.clineVersion ?? undefined;
        return message;
    },
};
function createBaseGetTelemetrySettingsResponse() {
    return { isEnabled: 0 };
}
export const GetTelemetrySettingsResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.isEnabled !== 0) {
            writer.uint32(8).int32(message.isEnabled);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetTelemetrySettingsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.isEnabled = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { isEnabled: isSet(object.isEnabled) ? settingFromJSON(object.isEnabled) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.isEnabled !== 0) {
            obj.isEnabled = settingToJSON(message.isEnabled);
        }
        return obj;
    },
    create(base) {
        return GetTelemetrySettingsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetTelemetrySettingsResponse();
        message.isEnabled = object.isEnabled ?? 0;
        return message;
    },
};
function createBaseTelemetrySettingsEvent() {
    return { isEnabled: 0 };
}
export const TelemetrySettingsEvent = {
    encode(message, writer = new BinaryWriter()) {
        if (message.isEnabled !== 0) {
            writer.uint32(8).int32(message.isEnabled);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseTelemetrySettingsEvent();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.isEnabled = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { isEnabled: isSet(object.isEnabled) ? settingFromJSON(object.isEnabled) : 0 };
    },
    toJSON(message) {
        const obj = {};
        if (message.isEnabled !== 0) {
            obj.isEnabled = settingToJSON(message.isEnabled);
        }
        return obj;
    },
    create(base) {
        return TelemetrySettingsEvent.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseTelemetrySettingsEvent();
        message.isEnabled = object.isEnabled ?? 0;
        return message;
    },
};
export const EnvServiceDefinition = {
    name: "EnvService",
    fullName: "host.EnvService",
    methods: {
        /** Writes text to the system clipboard. */
        clipboardWriteText: {
            name: "clipboardWriteText",
            requestType: StringRequest,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
        /** Reads text from the system clipboard. */
        clipboardReadText: {
            name: "clipboardReadText",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: String,
            responseStream: false,
            options: {},
        },
        /** Returns the name and version of the host IDE or environment. */
        getHostVersion: {
            name: "getHostVersion",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: GetHostVersionResponse,
            responseStream: false,
            options: {},
        },
        /**
         * Returns a URI that will redirect to the host environment.
         * e.g. vscode://saoudrizwan.claude-dev, idea://, pycharm://, etc.
         * If the host does not support URIs it should return empty.
         */
        getIdeRedirectUri: {
            name: "getIdeRedirectUri",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: String,
            responseStream: false,
            options: {},
        },
        /**
         * Returns the telemetry settings of the host environment. This may return UNSUPPORTED
         * if the host does not specify telemetry settings for the plugin.
         */
        getTelemetrySettings: {
            name: "getTelemetrySettings",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: GetTelemetrySettingsResponse,
            responseStream: false,
            options: {},
        },
        /** Returns events when the telemetry settings change. */
        subscribeToTelemetrySettings: {
            name: "subscribeToTelemetrySettings",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: TelemetrySettingsEvent,
            responseStream: true,
            options: {},
        },
        /** Initiates a graceful shutdown of the host bridge service. */
        shutdown: {
            name: "shutdown",
            requestType: EmptyRequest,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
    },
};
export const EnvServiceService = {
    /** Writes text to the system clipboard. */
    clipboardWriteText: {
        path: "/host.EnvService/clipboardWriteText",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(StringRequest.encode(value).finish()),
        requestDeserialize: (value) => StringRequest.decode(value),
        responseSerialize: (value) => Buffer.from(Empty.encode(value).finish()),
        responseDeserialize: (value) => Empty.decode(value),
    },
    /** Reads text from the system clipboard. */
    clipboardReadText: {
        path: "/host.EnvService/clipboardReadText",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(String.encode(value).finish()),
        responseDeserialize: (value) => String.decode(value),
    },
    /** Returns the name and version of the host IDE or environment. */
    getHostVersion: {
        path: "/host.EnvService/getHostVersion",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetHostVersionResponse.encode(value).finish()),
        responseDeserialize: (value) => GetHostVersionResponse.decode(value),
    },
    /**
     * Returns a URI that will redirect to the host environment.
     * e.g. vscode://saoudrizwan.claude-dev, idea://, pycharm://, etc.
     * If the host does not support URIs it should return empty.
     */
    getIdeRedirectUri: {
        path: "/host.EnvService/getIdeRedirectUri",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(String.encode(value).finish()),
        responseDeserialize: (value) => String.decode(value),
    },
    /**
     * Returns the telemetry settings of the host environment. This may return UNSUPPORTED
     * if the host does not specify telemetry settings for the plugin.
     */
    getTelemetrySettings: {
        path: "/host.EnvService/getTelemetrySettings",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetTelemetrySettingsResponse.encode(value).finish()),
        responseDeserialize: (value) => GetTelemetrySettingsResponse.decode(value),
    },
    /** Returns events when the telemetry settings change. */
    subscribeToTelemetrySettings: {
        path: "/host.EnvService/subscribeToTelemetrySettings",
        requestStream: false,
        responseStream: true,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(TelemetrySettingsEvent.encode(value).finish()),
        responseDeserialize: (value) => TelemetrySettingsEvent.decode(value),
    },
    /** Initiates a graceful shutdown of the host bridge service. */
    shutdown: {
        path: "/host.EnvService/shutdown",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EmptyRequest.encode(value).finish()),
        requestDeserialize: (value) => EmptyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(Empty.encode(value).finish()),
        responseDeserialize: (value) => Empty.decode(value),
    },
};
export const EnvServiceClient = makeGenericClientConstructor(EnvServiceService, "host.EnvService");
function isSet(value) {
    return value !== null && value !== undefined;
}
