// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: host/testing.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { makeGenericClientConstructor, } from "@grpc/grpc-js";
function createBaseGetWebviewHtmlRequest() {
    return {};
}
export const GetWebviewHtmlRequest = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetWebviewHtmlRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return GetWebviewHtmlRequest.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseGetWebviewHtmlRequest();
        return message;
    },
};
function createBaseGetWebviewHtmlResponse() {
    return { html: undefined };
}
export const GetWebviewHtmlResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.html !== undefined) {
            writer.uint32(10).string(message.html);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetWebviewHtmlResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.html = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { html: isSet(object.html) ? globalThis.String(object.html) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.html !== undefined) {
            obj.html = message.html;
        }
        return obj;
    },
    create(base) {
        return GetWebviewHtmlResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetWebviewHtmlResponse();
        message.html = object.html ?? undefined;
        return message;
    },
};
export const TestingServiceDefinition = {
    name: "TestingService",
    fullName: "host.TestingService",
    methods: {
        getWebviewHtml: {
            name: "getWebviewHtml",
            requestType: GetWebviewHtmlRequest,
            requestStream: false,
            responseType: GetWebviewHtmlResponse,
            responseStream: false,
            options: {},
        },
    },
};
export const TestingServiceService = {
    getWebviewHtml: {
        path: "/host.TestingService/getWebviewHtml",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetWebviewHtmlRequest.encode(value).finish()),
        requestDeserialize: (value) => GetWebviewHtmlRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetWebviewHtmlResponse.encode(value).finish()),
        responseDeserialize: (value) => GetWebviewHtmlResponse.decode(value),
    },
};
export const TestingServiceClient = makeGenericClientConstructor(TestingServiceService, "host.TestingService");
function isSet(value) {
    return value !== null && value !== undefined;
}
