// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: host/workspace.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { makeGenericClientConstructor, } from "@grpc/grpc-js";
import { FileDiagnostics, Metadata as Metadata1 } from "../cline/common.ts";
/** Optional selected type filter */
export var SearchWorkspaceItemsRequest_SearchItemType;
(function (SearchWorkspaceItemsRequest_SearchItemType) {
    SearchWorkspaceItemsRequest_SearchItemType[SearchWorkspaceItemsRequest_SearchItemType["FILE"] = 0] = "FILE";
    SearchWorkspaceItemsRequest_SearchItemType[SearchWorkspaceItemsRequest_SearchItemType["FOLDER"] = 1] = "FOLDER";
    SearchWorkspaceItemsRequest_SearchItemType[SearchWorkspaceItemsRequest_SearchItemType["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(SearchWorkspaceItemsRequest_SearchItemType || (SearchWorkspaceItemsRequest_SearchItemType = {}));
export function searchWorkspaceItemsRequest_SearchItemTypeFromJSON(object) {
    switch (object) {
        case 0:
        case "FILE":
            return SearchWorkspaceItemsRequest_SearchItemType.FILE;
        case 1:
        case "FOLDER":
            return SearchWorkspaceItemsRequest_SearchItemType.FOLDER;
        case -1:
        case "UNRECOGNIZED":
        default:
            return SearchWorkspaceItemsRequest_SearchItemType.UNRECOGNIZED;
    }
}
export function searchWorkspaceItemsRequest_SearchItemTypeToJSON(object) {
    switch (object) {
        case SearchWorkspaceItemsRequest_SearchItemType.FILE:
            return "FILE";
        case SearchWorkspaceItemsRequest_SearchItemType.FOLDER:
            return "FOLDER";
        case SearchWorkspaceItemsRequest_SearchItemType.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseGetWorkspacePathsRequest() {
    return { id: undefined };
}
export const GetWorkspacePathsRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.id !== undefined) {
            writer.uint32(10).string(message.id);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetWorkspacePathsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { id: isSet(object.id) ? globalThis.String(object.id) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== undefined) {
            obj.id = message.id;
        }
        return obj;
    },
    create(base) {
        return GetWorkspacePathsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetWorkspacePathsRequest();
        message.id = object.id ?? undefined;
        return message;
    },
};
function createBaseGetWorkspacePathsResponse() {
    return { id: undefined, paths: [] };
}
export const GetWorkspacePathsResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.id !== undefined) {
            writer.uint32(10).string(message.id);
        }
        for (const v of message.paths) {
            writer.uint32(18).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetWorkspacePathsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.paths.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            id: isSet(object.id) ? globalThis.String(object.id) : undefined,
            paths: globalThis.Array.isArray(object?.paths) ? object.paths.map((e) => globalThis.String(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== undefined) {
            obj.id = message.id;
        }
        if (message.paths?.length) {
            obj.paths = message.paths;
        }
        return obj;
    },
    create(base) {
        return GetWorkspacePathsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetWorkspacePathsResponse();
        message.id = object.id ?? undefined;
        message.paths = object.paths?.map((e) => e) || [];
        return message;
    },
};
function createBaseSaveOpenDocumentIfDirtyRequest() {
    return { filePath: undefined };
}
export const SaveOpenDocumentIfDirtyRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.filePath !== undefined) {
            writer.uint32(18).string(message.filePath);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSaveOpenDocumentIfDirtyRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.filePath = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { filePath: isSet(object.filePath) ? globalThis.String(object.filePath) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.filePath !== undefined) {
            obj.filePath = message.filePath;
        }
        return obj;
    },
    create(base) {
        return SaveOpenDocumentIfDirtyRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSaveOpenDocumentIfDirtyRequest();
        message.filePath = object.filePath ?? undefined;
        return message;
    },
};
function createBaseSaveOpenDocumentIfDirtyResponse() {
    return { wasSaved: undefined };
}
export const SaveOpenDocumentIfDirtyResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.wasSaved !== undefined) {
            writer.uint32(8).bool(message.wasSaved);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSaveOpenDocumentIfDirtyResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.wasSaved = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { wasSaved: isSet(object.wasSaved) ? globalThis.Boolean(object.wasSaved) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.wasSaved !== undefined) {
            obj.wasSaved = message.wasSaved;
        }
        return obj;
    },
    create(base) {
        return SaveOpenDocumentIfDirtyResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSaveOpenDocumentIfDirtyResponse();
        message.wasSaved = object.wasSaved ?? undefined;
        return message;
    },
};
function createBaseGetDiagnosticsRequest() {
    return { metadata: undefined };
}
export const GetDiagnosticsRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.metadata !== undefined) {
            Metadata1.encode(message.metadata, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetDiagnosticsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.metadata = Metadata1.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { metadata: isSet(object.metadata) ? Metadata1.fromJSON(object.metadata) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.metadata !== undefined) {
            obj.metadata = Metadata1.toJSON(message.metadata);
        }
        return obj;
    },
    create(base) {
        return GetDiagnosticsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetDiagnosticsRequest();
        message.metadata = (object.metadata !== undefined && object.metadata !== null)
            ? Metadata1.fromPartial(object.metadata)
            : undefined;
        return message;
    },
};
function createBaseGetDiagnosticsResponse() {
    return { fileDiagnostics: [] };
}
export const GetDiagnosticsResponse = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.fileDiagnostics) {
            FileDiagnostics.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetDiagnosticsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.fileDiagnostics.push(FileDiagnostics.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            fileDiagnostics: globalThis.Array.isArray(object?.fileDiagnostics)
                ? object.fileDiagnostics.map((e) => FileDiagnostics.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.fileDiagnostics?.length) {
            obj.fileDiagnostics = message.fileDiagnostics.map((e) => FileDiagnostics.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return GetDiagnosticsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetDiagnosticsResponse();
        message.fileDiagnostics = object.fileDiagnostics?.map((e) => FileDiagnostics.fromPartial(e)) || [];
        return message;
    },
};
function createBaseSearchWorkspaceItemsRequest() {
    return { query: "", limit: undefined, selectedType: undefined };
}
export const SearchWorkspaceItemsRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.query !== "") {
            writer.uint32(10).string(message.query);
        }
        if (message.limit !== undefined) {
            writer.uint32(16).int32(message.limit);
        }
        if (message.selectedType !== undefined) {
            writer.uint32(24).int32(message.selectedType);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSearchWorkspaceItemsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.query = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.limit = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.selectedType = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            query: isSet(object.query) ? globalThis.String(object.query) : "",
            limit: isSet(object.limit) ? globalThis.Number(object.limit) : undefined,
            selectedType: isSet(object.selectedType)
                ? searchWorkspaceItemsRequest_SearchItemTypeFromJSON(object.selectedType)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.query !== "") {
            obj.query = message.query;
        }
        if (message.limit !== undefined) {
            obj.limit = Math.round(message.limit);
        }
        if (message.selectedType !== undefined) {
            obj.selectedType = searchWorkspaceItemsRequest_SearchItemTypeToJSON(message.selectedType);
        }
        return obj;
    },
    create(base) {
        return SearchWorkspaceItemsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSearchWorkspaceItemsRequest();
        message.query = object.query ?? "";
        message.limit = object.limit ?? undefined;
        message.selectedType = object.selectedType ?? undefined;
        return message;
    },
};
function createBaseSearchWorkspaceItemsResponse() {
    return { items: [] };
}
export const SearchWorkspaceItemsResponse = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.items) {
            SearchWorkspaceItemsResponse_SearchItem.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSearchWorkspaceItemsResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.items.push(SearchWorkspaceItemsResponse_SearchItem.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            items: globalThis.Array.isArray(object?.items)
                ? object.items.map((e) => SearchWorkspaceItemsResponse_SearchItem.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.items?.length) {
            obj.items = message.items.map((e) => SearchWorkspaceItemsResponse_SearchItem.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return SearchWorkspaceItemsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSearchWorkspaceItemsResponse();
        message.items = object.items?.map((e) => SearchWorkspaceItemsResponse_SearchItem.fromPartial(e)) || [];
        return message;
    },
};
function createBaseSearchWorkspaceItemsResponse_SearchItem() {
    return { path: "", type: 0, label: undefined };
}
export const SearchWorkspaceItemsResponse_SearchItem = {
    encode(message, writer = new BinaryWriter()) {
        if (message.path !== "") {
            writer.uint32(10).string(message.path);
        }
        if (message.type !== 0) {
            writer.uint32(16).int32(message.type);
        }
        if (message.label !== undefined) {
            writer.uint32(26).string(message.label);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSearchWorkspaceItemsResponse_SearchItem();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.path = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.type = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.label = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            path: isSet(object.path) ? globalThis.String(object.path) : "",
            type: isSet(object.type) ? searchWorkspaceItemsRequest_SearchItemTypeFromJSON(object.type) : 0,
            label: isSet(object.label) ? globalThis.String(object.label) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.path !== "") {
            obj.path = message.path;
        }
        if (message.type !== 0) {
            obj.type = searchWorkspaceItemsRequest_SearchItemTypeToJSON(message.type);
        }
        if (message.label !== undefined) {
            obj.label = message.label;
        }
        return obj;
    },
    create(base) {
        return SearchWorkspaceItemsResponse_SearchItem.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSearchWorkspaceItemsResponse_SearchItem();
        message.path = object.path ?? "";
        message.type = object.type ?? 0;
        message.label = object.label ?? undefined;
        return message;
    },
};
function createBaseOpenProblemsPanelRequest() {
    return {};
}
export const OpenProblemsPanelRequest = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenProblemsPanelRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return OpenProblemsPanelRequest.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseOpenProblemsPanelRequest();
        return message;
    },
};
function createBaseOpenProblemsPanelResponse() {
    return {};
}
export const OpenProblemsPanelResponse = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenProblemsPanelResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return OpenProblemsPanelResponse.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseOpenProblemsPanelResponse();
        return message;
    },
};
function createBaseOpenInFileExplorerPanelRequest() {
    return { path: "" };
}
export const OpenInFileExplorerPanelRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.path !== "") {
            writer.uint32(10).string(message.path);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenInFileExplorerPanelRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.path = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { path: isSet(object.path) ? globalThis.String(object.path) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.path !== "") {
            obj.path = message.path;
        }
        return obj;
    },
    create(base) {
        return OpenInFileExplorerPanelRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseOpenInFileExplorerPanelRequest();
        message.path = object.path ?? "";
        return message;
    },
};
function createBaseOpenInFileExplorerPanelResponse() {
    return {};
}
export const OpenInFileExplorerPanelResponse = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenInFileExplorerPanelResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return OpenInFileExplorerPanelResponse.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseOpenInFileExplorerPanelResponse();
        return message;
    },
};
function createBaseOpenClineSidebarPanelRequest() {
    return {};
}
export const OpenClineSidebarPanelRequest = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenClineSidebarPanelRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return OpenClineSidebarPanelRequest.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseOpenClineSidebarPanelRequest();
        return message;
    },
};
function createBaseOpenClineSidebarPanelResponse() {
    return {};
}
export const OpenClineSidebarPanelResponse = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenClineSidebarPanelResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return OpenClineSidebarPanelResponse.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseOpenClineSidebarPanelResponse();
        return message;
    },
};
function createBaseOpenTerminalRequest() {
    return {};
}
export const OpenTerminalRequest = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenTerminalRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return OpenTerminalRequest.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseOpenTerminalRequest();
        return message;
    },
};
function createBaseOpenTerminalResponse() {
    return {};
}
export const OpenTerminalResponse = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOpenTerminalResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return OpenTerminalResponse.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseOpenTerminalResponse();
        return message;
    },
};
function createBaseExecuteCommandInTerminalRequest() {
    return { command: "" };
}
export const ExecuteCommandInTerminalRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.command !== "") {
            writer.uint32(10).string(message.command);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExecuteCommandInTerminalRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.command = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { command: isSet(object.command) ? globalThis.String(object.command) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.command !== "") {
            obj.command = message.command;
        }
        return obj;
    },
    create(base) {
        return ExecuteCommandInTerminalRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExecuteCommandInTerminalRequest();
        message.command = object.command ?? "";
        return message;
    },
};
function createBaseExecuteCommandInTerminalResponse() {
    return { success: false };
}
export const ExecuteCommandInTerminalResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.success !== false) {
            writer.uint32(8).bool(message.success);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExecuteCommandInTerminalResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.success = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
    },
    toJSON(message) {
        const obj = {};
        if (message.success !== false) {
            obj.success = message.success;
        }
        return obj;
    },
    create(base) {
        return ExecuteCommandInTerminalResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExecuteCommandInTerminalResponse();
        message.success = object.success ?? false;
        return message;
    },
};
export const WorkspaceServiceDefinition = {
    name: "WorkspaceService",
    fullName: "host.WorkspaceService",
    methods: {
        /** Returns a list of the top level directories of the workspace. */
        getWorkspacePaths: {
            name: "getWorkspacePaths",
            requestType: GetWorkspacePathsRequest,
            requestStream: false,
            responseType: GetWorkspacePathsResponse,
            responseStream: false,
            options: {},
        },
        /**
         * Saves an open document if it's open in the editor and has unsaved changes.
         * Returns true if the document was saved, returns false if the document was not found, or did not
         * need to be saved.
         */
        saveOpenDocumentIfDirty: {
            name: "saveOpenDocumentIfDirty",
            requestType: SaveOpenDocumentIfDirtyRequest,
            requestStream: false,
            responseType: SaveOpenDocumentIfDirtyResponse,
            responseStream: false,
            options: {},
        },
        /** Get diagnostics from the workspace. */
        getDiagnostics: {
            name: "getDiagnostics",
            requestType: GetDiagnosticsRequest,
            requestStream: false,
            responseType: GetDiagnosticsResponse,
            responseStream: false,
            options: {},
        },
        /** Makes the problems panel/pane visible in the IDE and focuses it. */
        openProblemsPanel: {
            name: "openProblemsPanel",
            requestType: OpenProblemsPanelRequest,
            requestStream: false,
            responseType: OpenProblemsPanelResponse,
            responseStream: false,
            options: {},
        },
        /** Opens the IDE file explorer panel and selects a file or directory. */
        openInFileExplorerPanel: {
            name: "openInFileExplorerPanel",
            requestType: OpenInFileExplorerPanelRequest,
            requestStream: false,
            responseType: OpenInFileExplorerPanelResponse,
            responseStream: false,
            options: {},
        },
        /** Opens and focuses the Cline sidebar panel in the host IDE. */
        openClineSidebarPanel: {
            name: "openClineSidebarPanel",
            requestType: OpenClineSidebarPanelRequest,
            requestStream: false,
            responseType: OpenClineSidebarPanelResponse,
            responseStream: false,
            options: {},
        },
        /** Opens and focuses the terminal panel. */
        openTerminalPanel: {
            name: "openTerminalPanel",
            requestType: OpenTerminalRequest,
            requestStream: false,
            responseType: OpenTerminalResponse,
            responseStream: false,
            options: {},
        },
        /** Executes a command in a new terminal */
        executeCommandInTerminal: {
            name: "executeCommandInTerminal",
            requestType: ExecuteCommandInTerminalRequest,
            requestStream: false,
            responseType: ExecuteCommandInTerminalResponse,
            responseStream: false,
            options: {},
        },
    },
};
export const WorkspaceServiceService = {
    /** Returns a list of the top level directories of the workspace. */
    getWorkspacePaths: {
        path: "/host.WorkspaceService/getWorkspacePaths",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetWorkspacePathsRequest.encode(value).finish()),
        requestDeserialize: (value) => GetWorkspacePathsRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetWorkspacePathsResponse.encode(value).finish()),
        responseDeserialize: (value) => GetWorkspacePathsResponse.decode(value),
    },
    /**
     * Saves an open document if it's open in the editor and has unsaved changes.
     * Returns true if the document was saved, returns false if the document was not found, or did not
     * need to be saved.
     */
    saveOpenDocumentIfDirty: {
        path: "/host.WorkspaceService/saveOpenDocumentIfDirty",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(SaveOpenDocumentIfDirtyRequest.encode(value).finish()),
        requestDeserialize: (value) => SaveOpenDocumentIfDirtyRequest.decode(value),
        responseSerialize: (value) => Buffer.from(SaveOpenDocumentIfDirtyResponse.encode(value).finish()),
        responseDeserialize: (value) => SaveOpenDocumentIfDirtyResponse.decode(value),
    },
    /** Get diagnostics from the workspace. */
    getDiagnostics: {
        path: "/host.WorkspaceService/getDiagnostics",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetDiagnosticsRequest.encode(value).finish()),
        requestDeserialize: (value) => GetDiagnosticsRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetDiagnosticsResponse.encode(value).finish()),
        responseDeserialize: (value) => GetDiagnosticsResponse.decode(value),
    },
    /** Makes the problems panel/pane visible in the IDE and focuses it. */
    openProblemsPanel: {
        path: "/host.WorkspaceService/openProblemsPanel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(OpenProblemsPanelRequest.encode(value).finish()),
        requestDeserialize: (value) => OpenProblemsPanelRequest.decode(value),
        responseSerialize: (value) => Buffer.from(OpenProblemsPanelResponse.encode(value).finish()),
        responseDeserialize: (value) => OpenProblemsPanelResponse.decode(value),
    },
    /** Opens the IDE file explorer panel and selects a file or directory. */
    openInFileExplorerPanel: {
        path: "/host.WorkspaceService/openInFileExplorerPanel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(OpenInFileExplorerPanelRequest.encode(value).finish()),
        requestDeserialize: (value) => OpenInFileExplorerPanelRequest.decode(value),
        responseSerialize: (value) => Buffer.from(OpenInFileExplorerPanelResponse.encode(value).finish()),
        responseDeserialize: (value) => OpenInFileExplorerPanelResponse.decode(value),
    },
    /** Opens and focuses the Cline sidebar panel in the host IDE. */
    openClineSidebarPanel: {
        path: "/host.WorkspaceService/openClineSidebarPanel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(OpenClineSidebarPanelRequest.encode(value).finish()),
        requestDeserialize: (value) => OpenClineSidebarPanelRequest.decode(value),
        responseSerialize: (value) => Buffer.from(OpenClineSidebarPanelResponse.encode(value).finish()),
        responseDeserialize: (value) => OpenClineSidebarPanelResponse.decode(value),
    },
    /** Opens and focuses the terminal panel. */
    openTerminalPanel: {
        path: "/host.WorkspaceService/openTerminalPanel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(OpenTerminalRequest.encode(value).finish()),
        requestDeserialize: (value) => OpenTerminalRequest.decode(value),
        responseSerialize: (value) => Buffer.from(OpenTerminalResponse.encode(value).finish()),
        responseDeserialize: (value) => OpenTerminalResponse.decode(value),
    },
    /** Executes a command in a new terminal */
    executeCommandInTerminal: {
        path: "/host.WorkspaceService/executeCommandInTerminal",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ExecuteCommandInTerminalRequest.encode(value).finish()),
        requestDeserialize: (value) => ExecuteCommandInTerminalRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ExecuteCommandInTerminalResponse.encode(value).finish()),
        responseDeserialize: (value) => ExecuteCommandInTerminalResponse.decode(value),
    },
};
export const WorkspaceServiceClient = makeGenericClientConstructor(WorkspaceServiceService, "host.WorkspaceService");
function isSet(value) {
    return value !== null && value !== undefined;
}
