// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1

/* eslint-disable */

export * from "./google/protobuf/timestamp.ts";
export * from "./google/protobuf/field_mask.ts";
